### ISSUE TITLE
Authentication strategies

### ISSUE THREAD

**Issue by JustSteveKing** [JustSteveKing/laravel-transporter#27]
When I am building a request with transporter, and it needs authentication, I typically add a method onto my Request that looks like:

```php
public function authenticate(): static
{
    $this->request->withToken(config('services.service-name.token'));

  return $this;
}
```

Which allows me to use it on requests as required:

```php
MyRequest::build()->authenticate()->send();
```

It works, and works well. But I can't help feel something is missing here. If we are really going for an OOP approach to API requests, surely there is something I could do here? My initial thoughts, that I would like some feedback on are:

```php
class MyRequest extends Request
{
  protected AuthStrategy $authStrategy;

  public function send(): Response
  {
    $this->authStrategy->apply($this->request);
    
    /** Rest of method */
  }
}
```

Allowing us to create our own AuthStrategies as required:

```php
interface AuthStrategy
{
  public function apply(PendingRequest $request): void;
}
```

Which allows:

```php
class ApiTokenStrategy implements AuthStrategy
{
  public function __construct(
    protected string $token,
  ) {}

  public function apply(PendingRequest $request): void
  {
    $request->withToken($this->token);
  }
}
```

The last step is something I need to figure out, how to get it to be added nicely, I had thought perhaps a Trait - but I am not sure. I am open to suggestions from others here.

**Comment by JustSteveKing** [comment]
Another option here, that just came to me:

```php
class MyRequest extends Request
{
  public function send(): Response
  {
    if (method_exists($this, 'authenticate')) {
      $this->applyAuth($this->request);
    }
    
    /** Rest of method */
  }
}
```

```php
trait HasApiToken
{
    public function authenticate(PendingRequest $request)
    {
      if (! isset($this->apiToken)) {
        throw new InvalidArgument("API Token missing");
      }
      
      $this->request->withToken(
        $this->apiToken,
        $this->apiTokenType ?? 'Bearer',
      );
    }
}
```

To utilise this:

```php
class MyRequest extends Request
{
  use HasApiToken;
  
  protected string $apiToken = '1234-1234-1234-1234';
  protected string $apiTokenType = 'Bearer';
}
```

However to do this effectively, we would need to find a nice way to pass through the API token information from config/env and not leave tokens exposed on classes like this.

**Comment by SamuelMwangiW** [comment]
Hi Steve,

To build on to this discussion, on the second I would suggest

```PHP
trait HasApiToken
{
    public function authenticate(PendingRequest $request)
    {
      if (! isset($this->apiToken())) {
        throw new InvalidArgument("API Token missing");
      }
      
      $this->request->withToken(
        $this->apiToken(),
        $this->apiTokenType(),
      );
    }

  protected function apiToken(): ?string
  {
      return $this->apiToken ?? null;
  }
 
  protected function apiTokenType(): string
  {
       return $this->apiTokenType ?? 'Bearer';
  }

}

```

This allows the user to override the `apiToken()` as follows and removes the need to to have the apiToken in the class unless if the user insists

```PHP
class MyRequest extends Request
{
  use HasApiToken;
  
  protected function apiToken(): ?string
  {
      return config('service.example.api');
  }
}

```

-----------
The first option (`AuthStrategy` interface) though looks like the more flexible option in my opinion as it allows strategies such as:
1. `BearerTokenStrategy` - Authorization: Bearer <token>
2. `BasicAuthenticationStrategy` - Authorization: Basic bG9sOnNlY3VyZQ==
3. `CustomHeaderStrategy` - apiKey: <MyAppApiKey>
4. `QueryStringStrategy` - authentication details appended to the query string because there are apis that do that in the year 2021 😆
5. `BodyDataStrategy` - Is this even a thing? 🤔

**Comment by JustSteveKing** [comment]
Hey @SamuelMwangiW thanks for this! It is actually a good idea and something I think we could use alongside an interface?

So what I have done in the past, and in [another library](https://github.com/JustSteveKing/php-sdk) is the have a NullableStrategy - which simply doesn't ammend the request in any way, but has the same blueprint method to make the trait resolve the interface requirements for the class.

I think if we can do it this way, it would work well.

```php
class YourRequest extends Request
{
    use TokenAuthentication;

    public function authenticate(null|string $token = null): static
    {
        $this->request->withToken(
            token: $token ?? config('services.your-service.token'),
        );
    }
}
```

The above could simply intersect on the send method using reflection to see if traits/methods are available - so basically "Just in time auth" basically, we don't care until we send - in which case we check, mutate the request, and send

**Comment by deanlj** [comment]
I really like the JIT auth idea.

The AuthStrategy classes feel a bit like over-engineering. 

I love Transporter because it's so clean and more importantly for me it's simple and quick to get going.

The NullableStrategy, personally feels the right way to go as it maintains the simplicity for the user and allows easy implementation.

Going back to Samuels point about flexibility, i think your last idea will work i.e. withToken as you've shown.

withHeader

```php
class YourRequest extends Request
{
    use TokenAuthentication;

    public function authenticate(null|string $token = null): static
    {         
        $request->withHeaders([
            'X-API-KEY' => config('services.your-service.api_key'),
         ]);
    }
}
```

You can even create your base class for a service and extend it for each request


```php
class YourRequestBaseClass extends Request
{
    use TokenAuthentication;

    public function authenticate(null|string $token = null): static
    {
        $this->request->withToken(
            token: $token ?? config('services.your-service.token'),
        );
    }
}
```


```php
class YourRequest extends YourRequestBaseClass
{
    // any request specific stuff here
}
```

**Comment by deanlj** [comment]
Just a thought, as the implementation is likely to be in user land so the trait could just be called Authentication or WithAuthentication.

Update the docs to show folks an example for using Bearer, Basic, Header etc

happy to do a PR for the docs once the code is done (wouldn't want to taint your nice codebase 🤪) but could help out on code if you want.

**Comment by SamuelMwangiW** [comment]
Hey @JustSteveKing and @deanlj. 

I got another idea and not sure if it makes sense: Have an `Authenticable` kind of contract that a `Request` class may implement. This contract would require that implements the `authenticate` method in the class. 

Then in the `send` method of the package class, check if the request is an instance of this `Authenticable` contract and if so, call `authenticate` method on the request class.

```php
interface Authenticable{
    protected function authenticate(): void;
}
```

```php
class YourRequestClass extends Request implelements Authenticable
{
    public function authenticate(): void
    {
        $this->request->withToken(
            token: config('services.your-service.token'),
        );
    }
}
```

This therefore devolve authentication implementation to user-land and live up to Transporter's ease of use. The user is therefore in a position to implement authentication as per the service requirements

**Comment by fred-oranje** [comment]
Hi @JustSteveKing,

I was thinking about something more along the lines of a form of middleware. Opens up more possibilities other than authentication.

# The Simple Way

So a simple contract which allows the middleware to access to public methods of the request object:

```php
<?php

declare(strict_types=1);

namespace JustSteveKing\Transporter\Contracts;

use JustSteveKing\Transporter\Request;

interface Middleware
{
    public function handle(Request $request): void;
}
```

And then a protected middleware array in the request object which the user can fill with instances of middleware objects. In PHP 8.1 you would be able to that directly in the class definition if I remember correctly. Otherwise in the constructor, or maybe a special method which can be overridden returning middleware.

```php
<?php

class MyRequest extends \JustSteveKing\Transporter\Request
{
   protected array $middleware = [
      new TokenAuthentication(config('services.my-token')),
   ];
}
```

Also a method withMiddleware could be added to inject middleware later on in the proces. Then in the `send()` and `buildForConcurrent()` methods we would run through the middleware handle methods:

```php
foreach ($this->middleware as $middleware) {
   $middleware->handle($this);
}
```

# The more complex way

I was also thinking about rate limited API request middleware, where if you already know you went over the limit you wouldn't want to send the request, but return a rate limit HTTP response in advance. In this case the middleware should work more like Laravel's middleware, with a pipeline and the handle method having the $next variable. But in this case things need to moved around a bit more to work in concurrent request as well. I will to do some more thinking on this.

Please let me know your thoughts, I might whip up a prototype pull request tomorrow when I'm more clear headed.

**Comment by JustSteveKing** [comment]
@fred-oranje this actually sounds like it could be a great idea for more than just authentication

**Comment by fred-oranje** [comment]
@JustSteveKing, I made an attempt at writing the middleware part. It is currently visible under the middleware branch at https://github.com/fred-oranje/laravel-transporter/tree/middleware .

I have made a pull request regarding some bugs in concurrent requests, which might be a bit controversial in its implementation, so I'm holding off on the middleware pull request until you have had a chance to review the changes. I can always alter the middleware branch so that it only works for non concurrent requests, or for when you have a better solution to the concurrent request bugs.

**Comment by JustSteveKing** [comment]
@fred-oranje thanks! I will make sure I have a look at it!

**Comment by JustSteveKing** [comment]
Hey @fred-oranje - your PR for the PendingRequest fix has now been merged, feel free to PR the above if you still want to! It sounds like the most flexible and usable solution 😄

**Comment by JustSteveKing** [comment]
Closing this for now, but will revisit in the future. I think the middleware approach is the best idea, however figuring out the concurrent way to do it is something different that needs exploring.
